### ISSUE TITLE
[Error] Inconsistent value of measurement frequency

### ISSUE THREAD

**Issue by ghost** [Mirkes/AccelerometerCWA2BINConverter#2]
Hello,

I use Linux Mint 32Bits.
I ran your Java program to convert a .cwa file into a .bin file. However, I got these errors after doing the command `java cwa2bin file.cwa` :

`
Test of the file ./README.md
Test of the file ./cwa2bin.class
Test of the file ./cwa2bin.java
Test of the file ./cwa2bin.r
Test of the file ./file.bin
Test of the file ./file.cwa
processing of the file ./file.cwa
Inconsistent value of measurement frequency: there is 0 in header and 800 in the block 0Inconsistent value of measurement frequency: there is 0 in header and 117 in the block 1Inconsistent value of measurement frequency: there is 0 in header and 400 in the block 2java.lang.ArrayIndexOutOfBoundsException: 23186
at cwa2bin.convert(cwa2bin.java:392)
at cwa2bin.main(cwa2bin.java:96)
Error of reading/writing file file.bin: java.lang.ArrayIndexOutOfBoundsException: 23186
`
So I guess the problem is in my file.cwa, but do you have any idea how to resolve this ? Thanks for help

**Comment by Mirkes** [comment]
According to your report I found the following 
Inconsistent value of measurement frequency: there is 0 in header and 800 in the block 0
Inconsistent value of measurement frequency: there is 0 in header and 117 in the block 1
Inconsistent value of measurement frequency: there is 0 in header and 400 in the block 2
This means that in header of CWA file frequency is specified as 0Hz, and in each next block different frequency is specified.
This means that your file is essentially corrapted or your file has format which is not implemented in used convertor.
I think that the best way is to try usage of original firmware to check integrity of file. If your file will be correctly processed by firmware then it was formed in new format, otherwise you have correpted file.

Best regards,
Evgeny
